name: iris_sound_player
description: A audio Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.18                  # W, https://pub.dev/packages/just_audio
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: